// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMBUCe1rbRT_oEvZ9VC9MQTGoHEKt-lN4',
    appId: '1:932625770282:web:50cf7fa9fa9ff25d612053',
    messagingSenderId: '932625770282',
    projectId: 'tripper-356114',
    authDomain: 'tripper-356114.firebaseapp.com',
    storageBucket: 'tripper-356114.appspot.com',
    measurementId: 'G-GLK50YP0BH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYgwci7TUDRTJPy6XkOAOJ70p2YQfmt2o',
    appId: '1:932625770282:android:c44cd469da123404612053',
    messagingSenderId: '932625770282',
    projectId: 'tripper-356114',
    storageBucket: 'tripper-356114.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWbzsDBxYVD1nign6_7JpBWUStDvhWjYI',
    appId: '1:932625770282:ios:ed96a86fbe99a5d3612053',
    messagingSenderId: '932625770282',
    projectId: 'tripper-356114',
    storageBucket: 'tripper-356114.appspot.com',
    iosClientId: '932625770282-kni5l1v01bvnckula36p2tg0rhh9cf3m.apps.googleusercontent.com',
    iosBundleId: 'com.yhakamay.tripper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWbzsDBxYVD1nign6_7JpBWUStDvhWjYI',
    appId: '1:932625770282:ios:ed96a86fbe99a5d3612053',
    messagingSenderId: '932625770282',
    projectId: 'tripper-356114',
    storageBucket: 'tripper-356114.appspot.com',
    iosClientId: '932625770282-kni5l1v01bvnckula36p2tg0rhh9cf3m.apps.googleusercontent.com',
    iosBundleId: 'com.yhakamay.tripper',
  );
}
